'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.HTTPSTATUS = void 0;
/**
 * HTTP status codes enum
 */
var HTTPSTATUS;
(function (HTTPSTATUS) {
  HTTPSTATUS[(HTTPSTATUS['CREATED'] = 201)] = 'CREATED';
  HTTPSTATUS[(HTTPSTATUS['SUCCESS'] = 200)] = 'SUCCESS';
  HTTPSTATUS[(HTTPSTATUS['NOCONTENT'] = 204)] = 'NOCONTENT';
  HTTPSTATUS[(HTTPSTATUS['BADREQUEST'] = 400)] = 'BADREQUEST';
  HTTPSTATUS[(HTTPSTATUS['UNAUTHORIZED'] = 401)] = 'UNAUTHORIZED';
  HTTPSTATUS[(HTTPSTATUS['FORBIDDEN'] = 403)] = 'FORBIDDEN';
  HTTPSTATUS[(HTTPSTATUS['NOTFOUND'] = 404)] = 'NOTFOUND';
  HTTPSTATUS[(HTTPSTATUS['CONFLICT'] = 409)] = 'CONFLICT';
  HTTPSTATUS[(HTTPSTATUS['UNSUPPORTED'] = 415)] = 'UNSUPPORTED';
  HTTPSTATUS[(HTTPSTATUS['SERVERERROR'] = 500)] = 'SERVERERROR';
  HTTPSTATUS[(HTTPSTATUS['UNAVAILABLE'] = 503)] = 'UNAVAILABLE';
})(HTTPSTATUS || (exports.HTTPSTATUS = HTTPSTATUS = {}));
